import json

from sqlalchemy.orm import Session

from app.auth import hash_password
from app.database import SessionLocal
from app.models import CelestialObject, QuizQuestion, User

OBJECTS = [
    dict(
        slug="mercurio",
        name="Mercurio",
        type="planet",
        astronomy_body="mercury",
        magnitude=-0.4,
        distance="57.9 millones de km del Sol",
        diameter="4 879 km",
        fun_fact="Un día en Mercurio dura más que su año: 176 días terrestres vs 88 de órbita.",
        explain_beginner="Mercurio es el planeta más cercano al Sol y el más pequeño del sistema solar. No tiene atmósfera densa, así que de día quema y de noche hiela.",
        explain_medium="Mercurio es un mundo rocoso con campo magnético débil y gran núcleo de hierro. Su superficie llena de cráteres recuerda a la Luna.",
        explain_advanced="La resonancia 3:2 de Mercurio y su excentricidad orbital (e≈0.205) producen amaneceres dobles. MESSENGER y BepiColombo estudian su núcleo y volátiles polares.",
        image_query="Mercury planet MESSENGER",
        tags="planeta rocoso sol calor",
        best_months="amanecer y atardecer, cerca del Sol",
    ),
    dict(
        slug="venus",
        name="Venus",
        type="planet",
        astronomy_body="venus",
        magnitude=-4.6,
        distance="108 millones de km del Sol",
        diameter="12 104 km",
        fun_fact="Venus gira al revés: el Sol sale por el oeste.",
        explain_beginner="Venus es el objeto más brillante del cielo después del Sol y la Luna. Se le llama lucero del alba o del atardecer.",
        explain_medium="Venus tiene efecto invernadero desbocado: 460 °C y presión 90 veces la terrestre. Las nubes de ácido sulfúrico reflejan mucha luz.",
        explain_advanced="El albedo de Venus (~0.75) y su rotación retrógrada (periodo sidéreo −243 d) lo hacen único. Magellan y Akatsuki mapearon vulcanismo y superrotación.",
        image_query="Venus planet clouds",
        tags="planeta lucero invernadero",
        best_months="atardecer o amanecer",
    ),
    dict(
        slug="tierra",
        name="Tierra",
        type="planet",
        distance="149.6 millones de km del Sol (1 ua)",
        diameter="12 742 km",
        fun_fact="Es el único mundo conocido con vida y agua líquida estable en superficie.",
        explain_beginner="La Tierra es nuestro hogar: un planeta azul con océanos, atmósfera de nitrógeno y oxígeno, y un satélite grande: la Luna.",
        explain_medium="La tectónica de placas, el campo magnético y el ciclo del carbono regulan el clima. La inclinación de 23.4° causa las estaciones.",
        explain_advanced="La Tierra está en la zona habitable. El núcleo de hierro-níquel genera magnetósfera. El albedo Bond es ~0.30.",
        image_query="Earth from space NASA",
        tags="planeta hogar agua vida",
        best_months="siempre (estás encima)",
    ),
    dict(
        slug="marte",
        name="Marte",
        type="planet",
        astronomy_body="mars",
        magnitude=-2.0,
        distance="227.9 millones de km del Sol",
        diameter="6 779 km",
        fun_fact="Olympus Mons es el volcán más alto del sistema solar: unos 22 km.",
        explain_beginner="Marte es el planeta rojo. Tiene casquetes polares, tormentas de polvo y dos lunas pequeñas: Fobos y Deimos.",
        explain_medium="El color rojo viene del óxido de hierro. Hubo ríos y lagos hace miles de millones de años. Hoy el agua está sobre todo en hielo.",
        explain_advanced="Marte tiene atmósfera de CO2 a ~6 mbar. Perseverance y Curiosity analizan geoquímica. El eje inclinado ~25° produce estaciones.",
        image_query="Mars planet surface rover",
        tags="planeta rojo rover",
        best_months="oposiciones (cada 26 meses)",
    ),
    dict(
        slug="jupiter",
        name="Júpiter",
        type="planet",
        astronomy_body="jupiter",
        magnitude=-2.2,
        distance="778 millones de km del Sol",
        diameter="139 820 km",
        fun_fact="La Gran Mancha Roja es una tormenta más ancha que la Tierra y lleva siglos activa.",
        explain_beginner="Júpiter es el planeta más grande. Es un gigante de gas con rayas de nubes y muchas lunas, entre ellas Europa e Ío.",
        explain_medium="Júpiter protege en parte el sistema interior desviando cometas. Con prismáticos se ven sus cuatro lunas galileanas.",
        explain_advanced="Júpiter emite más calor del que recibe. Su magnetósfera es enorme. Juno mapea el campo gravitatorio y la metalicidad.",
        image_query="Jupiter planet Hubble Juno",
        tags="planeta gigante gas mancha",
        best_months="cuando está en oposición",
    ),
    dict(
        slug="saturno",
        name="Saturno",
        type="planet",
        astronomy_body="saturn",
        magnitude=0.5,
        distance="1 434 millones de km del Sol",
        diameter="116 460 km",
        fun_fact="Saturno podría flotar en una bañera gigante: su densidad media es menor que la del agua.",
        explain_beginner="Saturno es famoso por sus anillos brillantes de hielo y roca. También es un gigante gaseoso.",
        explain_medium="Los anillos se extienden cientos de miles de km pero tienen pocos metros de espesor. Titán tiene lagos de metano.",
        explain_advanced="Cassini reveló géiseres en Encélado y el hexágono polar. Las divisiones de Cassini y Encke se deben a resonancias.",
        image_query="Saturn rings Cassini",
        tags="planeta anillos titan",
        best_months="oposición, anillos abiertos",
    ),
    dict(
        slug="urano",
        name="Urano",
        type="planet",
        astronomy_body="uranus",
        magnitude=5.7,
        distance="2 871 millones de km del Sol",
        diameter="50 724 km",
        fun_fact="Urano rueda de lado: su eje está inclinado unos 98°.",
        explain_beginner="Urano es un gigante de hielo de color verde-azulado, muy lejos y difícil de ver a simple vista.",
        explain_medium="Su color viene del metano, que absorbe el rojo. Fue el primer planeta descubierto con telescopio, por Herschel en 1781.",
        explain_advanced="Urano y Neptuno son gigantes helados. El campo magnético está desplazado del centro y muy inclinado.",
        image_query="Uranus planet Voyager",
        tags="planeta hielo inclinado",
        best_months="con cielos oscuros y telescopio",
    ),
    dict(
        slug="neptuno",
        name="Neptuno",
        type="planet",
        astronomy_body="neptune",
        magnitude=7.8,
        distance="4 495 millones de km del Sol",
        diameter="49 244 km",
        fun_fact="Sus vientos superan los 2 000 km/h, los más rápidos del sistema solar.",
        explain_beginner="Neptuno es el último planeta. Es azul intenso y tiene lunas como Tritón. No se ve a simple vista.",
        explain_medium="Se predijo con matemáticas antes de observarse (1846), por perturbaciones en Urano. Voyager 2 es la única sonda que lo visitó.",
        explain_advanced="El calor interno alimenta meteorología violenta. Tritón orbita retrógrado: posible mundo capturado del cinturón de Kuiper.",
        image_query="Neptune planet Voyager 2",
        tags="planeta azul vientos",
        best_months="telescopio, lejos de ciudades",
    ),
    dict(
        slug="luna",
        name="Luna",
        type="moon",
        astronomy_body="moon",
        magnitude=-12.7,
        distance="384 400 km de la Tierra",
        diameter="3 474 km",
        fun_fact="Siempre vemos la misma cara porque está en rotación síncrona.",
        explain_beginner="La Luna es el satélite natural de la Tierra. Cambia de fase cada mes y provoca las mareas.",
        explain_medium="Sus mares son llanuras de basalto. Los cráteres cuentan impactos de miles de millones de años. Apollo 11 alunizó en 1969.",
        explain_advanced="La Luna se aleja ~3.8 cm/año. Su origen más aceptado es el impacto gigante Theia.",
        image_query="Moon surface crater NASA",
        tags="satelite fases mareas",
        best_months="casi todas las noches",
    ),
    dict(
        slug="sol",
        name="Sol",
        type="star",
        astronomy_body="sun",
        magnitude=-26.7,
        distance="1 ua / 8 minutos luz",
        diameter="1.39 millones de km",
        fun_fact="Cada segundo convierte unos 600 millones de toneladas de hidrógeno en helio.",
        explain_beginner="El Sol es una estrella: una bola enorme de gas caliente que nos da luz y calor. Nunca lo mires sin filtro solar certificado.",
        explain_medium="Es una enana amarilla tipo G2V. En su núcleo hay fusión nuclear. Las manchas solares marcan el ciclo de 11 años.",
        explain_advanced="El modelo estándar solar combina transporte radiativo y convectivo. Neutrinos y heliosismología confirman el dínamo magnético.",
        image_query="Sun solar disk NASA SDO",
        tags="estrella fusion luz",
        best_months="de día, con filtro solar",
    ),
    dict(
        slug="sirio",
        name="Sirio",
        type="star",
        magnitude=-1.46,
        ra_hours=6.7525,
        dec_deg=-16.7161,
        constellation="Can Mayor",
        distance="8.6 años luz",
        diameter="~1.7 radios solares (Sirio A)",
        fun_fact="Es la estrella más brillante del cielo nocturno y tiene una compañera enana blanca: Sirio B.",
        explain_beginner="Sirio es esa estrella muy brillante que ves en las noches de invierno (hemisferio norte) cerca de Orión.",
        explain_medium="Sirio A es tipo A1V, más caliente y masiva que el Sol. Forma un sistema binario con Sirio B.",
        explain_advanced="El par Sirio A/B tiene periodo ~50 años. Sirio B ilustra el límite de Chandrasekhar.",
        image_query="Sirius star night sky",
        tags="estrella brillante can mayor",
        best_months="diciembre a marzo",
    ),
    dict(
        slug="betelgeuse",
        name="Betelgeuse",
        type="star",
        magnitude=0.4,
        ra_hours=5.9195,
        dec_deg=7.4071,
        constellation="Orión",
        distance="~550 años luz",
        diameter="cientos de radios solares",
        fun_fact="Si estuviera en el lugar del Sol, engulliría a la Tierra y hasta a Júpiter.",
        explain_beginner="Betelgeuse es la estrella roja del hombro de Orión. Es una supergigante y algún día explotará como supernova.",
        explain_medium="Varía de brillo. En 2019-2020 se atenuó por una nube de polvo. No explotará mañana, pero está cerca del final.",
        explain_advanced="Es una supergigante M1-2Ia-ab con pérdida de masa. Interferometría resuelve su fotosfera y puntos calientes.",
        image_query="Betelgeuse Orion star",
        tags="supergigante orion roja",
        best_months="diciembre a marzo",
    ),
    dict(
        slug="vega",
        name="Vega",
        type="star",
        magnitude=0.03,
        ra_hours=18.6156,
        dec_deg=38.7837,
        constellation="Lira",
        distance="25 años luz",
        diameter="~2.4 radios solares",
        fun_fact="Fue la estrella polar hace 14 000 años y lo será otra vez por la precesión terrestre.",
        explain_beginner="Vega es una de las estrellas más brillantes del verano boreal y forma el Triángulo de verano.",
        explain_medium="Es tipo A0V, gira muy rápido y tiene un disco de polvo. Se usó como referencia de magnitud cero.",
        explain_advanced="Vega es un calibrador fotométrico. Interferometría muestra achatamiento por rotación cercana al límite de ruptura.",
        image_query="Vega star Lyra",
        tags="estrella lira verano",
        best_months="junio a septiembre",
    ),
    dict(
        slug="polaris",
        name="Polaris (Estrella Polar)",
        type="star",
        magnitude=2.0,
        ra_hours=2.5303,
        dec_deg=89.2641,
        constellation="Osa Menor",
        distance="~430 años luz",
        diameter="supergigante ~45 R☉ (Polaris Aa)",
        fun_fact="Casi no se mueve en el cielo del norte: todo el cielo parece girar a su alrededor.",
        explain_beginner="La Estrella Polar indica el norte. Si la encuentras, puedes orientarte sin brújula.",
        explain_medium="No es la más brillante. Es una cefeida de baja amplitud. En el hemisferio sur no se ve.",
        explain_advanced="Polaris Aa es una cefeida clásica en sistema triple. La precesión moverá el polo hacia Vega en ~12 000 años.",
        image_query="Polaris north star",
        tags="estrella norte osa menor",
        best_months="todo el año (hemisferio norte)",
    ),
    dict(
        slug="andromeda",
        name="Galaxia de Andrómeda (M31)",
        type="galaxy",
        magnitude=3.4,
        ra_hours=0.7122,
        dec_deg=41.2692,
        constellation="Andrómeda",
        distance="2.5 millones de años luz",
        diameter="~220 000 años luz",
        fun_fact="Es el objeto más lejano que mucha gente puede ver a simple vista en un cielo oscuro.",
        explain_beginner="Andrómeda es otra galaxia enorme, vecina de la Vía Láctea. Es una mancha suave, no una estrella puntual.",
        explain_medium="Tiene alrededor de un billón de estrellas. En ~4 500 millones de años colisionará con la Vía Láctea.",
        explain_advanced="M31 es una espiral Sb con halo de materia oscura. El núcleo es doble en proyección.",
        image_query="Andromeda galaxy M31",
        tags="galaxia espiral m31",
        best_months="octubre a enero",
    ),
    dict(
        slug="via-lactea",
        name="Vía Láctea",
        type="galaxy",
        constellation="Sagitario (centro)",
        distance="el Sol está a ~27 000 a.l. del centro",
        diameter="~100 000 años luz",
        fun_fact="El centro galáctico alberga un agujero negro supermasivo: Sagitario A*.",
        explain_beginner="La Vía Láctea es nuestra galaxia. En cielos oscuros se ve como una banda lechosa de estrellas.",
        explain_medium="Es una espiral barrada. El Sol tarda ~230 millones de años en dar una vuelta (año galáctico).",
        explain_advanced="Gaia cartografía mil millones de estrellas. Sgr A* tiene ~4.3 millones de masas solares.",
        image_query="Milky Way night sky center",
        tags="galaxia hogar sagitario",
        best_months="junio a septiembre (centro)",
    ),
    dict(
        slug="aurora",
        name="Aurora polar",
        type="phenomenon",
        fun_fact="El color verde típico lo emite el oxígeno a unos 100-150 km de altura.",
        explain_beginner="Las auroras son luces danzantes cerca de los polos. Ocurren cuando el Sol envía partículas que chocan con nuestra atmósfera.",
        explain_medium="El viento solar distorsiona la magnetosfera. Electrones acelerados excitan oxígeno y nitrógeno: verde, rojo y a veces púrpura.",
        explain_advanced="Las auroras trazan óvalos ligados a líneas de campo. El índice Kp y el viento solar predicen visibilidad.",
        image_query="aurora borealis earth",
        tags="fenomeno luces polar",
        best_months="equinoccios, alta actividad solar",
        distance="100-400 km de altitud",
        diameter="óvalos de miles de km",
    ),
    dict(
        slug="eclipse-solar",
        name="Eclipse solar",
        type="phenomenon",
        fun_fact="La coincidencia de tamaños angulares Sol-Luna es temporal: la Luna se aleja y los totales dejarán de ocurrir.",
        explain_beginner="Un eclipse solar pasa cuando la Luna se pone delante del Sol. Nunca se mira sin protección adecuada.",
        explain_medium="Hay totales, parciales y anulares. La umbra es el cono de sombra total; la penumbra da eclipse parcial.",
        explain_advanced="Los eclipses siguen el ciclo de Saros (~18 años 11 días). El parámetro gamma describe la geometría del cono.",
        image_query="solar eclipse corona",
        tags="fenomeno sol luna sombra",
        best_months="según el saros local",
        distance="alineación Tierra-Luna-Sol",
        diameter="umbra de pocos km a ~250 km",
    ),
    dict(
        slug="perseidas",
        name="Lluvia de Perseidas",
        type="phenomenon",
        ra_hours=3.233,
        dec_deg=58.0,
        constellation="Perseo",
        fun_fact="Los meteoros son restos del cometa 109P/Swift-Tuttle que se queman en la atmósfera.",
        explain_beginner="Las Perseidas son estrellas fugaces de agosto. Aparecen de repente y duran menos de un segundo.",
        explain_medium="El radiante está en Perseo. En el máximo se pueden ver decenas de meteoros por hora lejos de la ciudad.",
        explain_advanced="La velocidad de encuentro es ~59 km/s. El ZHR teórico ronda 100.",
        image_query="Perseid meteor shower",
        tags="fenomeno meteoros agosto",
        best_months="10-13 de agosto",
        distance="se queman a ~80-100 km",
        diameter="granos de polvo milimétricos",
    ),
    dict(
        slug="agujero-negro",
        name="Agujero negro",
        type="phenomenon",
        fun_fact="El primer retrato de uno fue M87* por el Event Horizon Telescope en 2019.",
        explain_beginner="Un agujero negro es un lugar del espacio donde la gravedad es tan fuerte que ni la luz sale. No es un aspirador cósmico.",
        explain_medium="Nacen al colapsar estrellas muy masivas o en núcleos de galaxias. Tienen un horizonte de sucesos: una frontera de no retorno.",
        explain_advanced="La métrica de Kerr describe agujeros rotantes. LIGO/Virgo/KAGRA miden fusiones de binarias compactas.",
        image_query="black hole M87 EHT",
        tags="fenomeno gravedad horizonte",
        best_months="se observan por efectos, no a ojo",
        distance="variable (estelar o supermasivo)",
        diameter="radio de Schwarzschild 2GM/c²",
    ),
]

QUESTIONS = [
    ("marte", "beginner", "¿Por qué Marte se ve rojizo?", ["Por óxido de hierro en su suelo", "Porque está más caliente que el Sol", "Por anillos de polvo azul", "Porque no tiene atmósfera"], 0, "El regolito marciano es rico en óxidos de hierro."),
    ("jupiter", "beginner", "Júpiter es principalmente un planeta de…", ["Roca sólida como la Tierra", "Gas (hidrógeno y helio)", "Hielo puro de agua", "Lava continua"], 1, "Es un gigante gaseoso sin superficie sólida como la nuestra."),
    ("saturno", "beginner", "¿Qué hace famoso a Saturno con un telescopio pequeño?", ["Sus anillos", "Tener océanos azules", "Ser el más cercano al Sol", "No tener lunas"], 0, "Los anillos de hielo y roca son su rasgo más icónico."),
    ("luna", "beginner", "Las fases de la Luna se deben a…", ["Que la Tierra tapa al Sol cada noche", "La porción iluminada por el Sol que vemos desde la Tierra", "Que la Luna se apaga", "Nubes en la Luna"], 1, "Siempre está iluminada a medias; cambia el ángulo de visión."),
    ("venus", "intermediate", "Venus es tan brillante sobre todo porque…", ["Está cubierto de nubes muy reflectantes", "Emite luz propia como una estrella", "Está más cerca que la Luna", "Tiene anillos de diamante"], 0, "Su albedo es de los más altos del sistema solar."),
    ("sol", "intermediate", "En el núcleo del Sol ocurre…", ["Fusión de hidrógeno en helio", "Combustión química de oxígeno", "Fisión de uranio", "Nada, solo brilla por magia"], 0, "La fusión nuclear sostiene su luminosidad."),
    ("andromeda", "intermediate", "Andrómeda es…", ["Una estrella doble", "Una galaxia espiral vecina", "Un planeta extrasolar", "Una nebulosa planetaria"], 1, "M31 es la galaxia espiral más cercana de gran tamaño."),
    ("polaris", "beginner", "Polaris sirve para…", ["Encontrar el sur en todo el planeta", "Orientarse hacia el norte en el hemisferio norte", "Medir la temperatura del Sol", "Ver auroras"], 1, "Está casi sobre el polo norte celeste."),
    ("betelgeuse", "advanced", "Betelgeuse es una…", ["Enana blanca", "Supergigante roja cercana al fin de su vida", "Estrella de neutrones", "Enana marrón"], 1, "Es una supergigante M que terminará en supernova."),
    ("neptuno", "advanced", "Neptuno se descubrió principalmente gracias a…", ["Un cometa que lo tapó", "Cálculos de perturbaciones en la órbita de Urano", "Se veía a simple vista siempre", "Señales de radio amateur"], 1, "Le Verrier y Adams predijeron su posición; Galle lo observó en 1846."),
    ("aurora", "intermediate", "Las auroras se producen cuando…", ["La Luna refleja el océano", "Partículas solares excitan gases de la alta atmósfera", "Los aviones dejan estelas de color", "Marte oculta a Venus"], 1, "El viento solar y la magnetosfera aceleran partículas hacia las regiones polares."),
    ("perseidas", "beginner", "Las Perseidas son…", ["Un planeta enano", "Una lluvia de meteoros de agosto", "Un tipo de galaxia", "Manchas solares"], 1, "Restos del cometa Swift-Tuttle que cruzan la Tierra cada agosto."),
    ("agujero-negro", "advanced", "El horizonte de sucesos es…", ["La superficie sólida del agujero negro", "La frontera de la que no escapa la luz", "Un anillo de asteroides", "La corona solar"], 1, "Es una superficie causal, no una superficie material."),
    ("via-lactea", "beginner", "La banda lechosa del cielo oscuro es…", ["Nubes de lluvia iluminadas", "Nuestra galaxia vista de canto", "El arcoíris nocturno", "Polvo de la Luna"], 1, "Son miles de millones de estrellas y polvo del disco galáctico."),
    ("mercurio", "intermediate", "Mercurio completa una órbita alrededor del Sol en unos…", ["88 días terrestres", "365 días", "12 años", "2 horas"], 0, "Su año es el más corto de los planetas."),
]


def seed_if_empty() -> None:
    db: Session = SessionLocal()
    try:
        if db.query(CelestialObject).first():
            return
        created = {}
        for item in OBJECTS:
            obj = CelestialObject(**item)
            db.add(obj)
            db.flush()
            created[obj.slug] = obj
        for slug, level, question, options, correct, explanation in QUESTIONS:
            db.add(
                QuizQuestion(
                    object_id=created[slug].id if slug in created else None,
                    level=level,
                    question=question,
                    options=json.dumps(options, ensure_ascii=False),
                    correct_index=correct,
                    explanation=explanation,
                )
            )
        db.add(
            User(
                name="Luna Exploradora",
                email="luna@astroia.dev",
                password_hash=hash_password("astroia123"),
                level="beginner",
                city="Bogotá",
                latitude=4.711,
                longitude=-74.0721,
            )
        )
        db.commit()
        print("Base de datos inicializada con catálogo, quiz y usuario demo.")
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()
